hapi:
  fhir:
    # Just in case we want to allow dynamic IG changes
    # Ideally they're loaded once on first startup from simplifier
    ig_runtime_upload_enabled: true
    # This should allow the $validate operator to function
    # enable_repository_validating_interceptor: true
    subscription:
      resthook_enabled: true
    # implementationguides:
    #   hl7_fhir_r4_core:
    #     name: hl7.fhir.r4.core
    #     version: 4.0.1
    #     url: https://packages.simplifier.net/hl7.fhir.r4.core/4.0.1
    #     installMode: STORE_AND_INSTALL
    #     reloadExisting: false
      # hl7_fhir_uv_ips:
      #   name: hl7.fhir.uv.ips
      #   version: 1.0.0
      #   url: https://packages.simplifier.net/hl7.fhir.uv.ips/1.0.0
      #   # installMode: STORE_AND_INSTALL
      #   reloadExisting: false
      # hl7_terminology_r4:
      #   name: hl7.terminology.r4
      #   version: 5.5.0
      #   url: https://packages.simplifier.net/hl7.terminology.r4/5.5.0
      #   # installMode: STORE_AND_INSTALL
      #   reloadExisting: false
      # ihe_mhd_fhir:
      #   name: ihe.mhd.fhir
      #   version: 4.0.1
      #   url: https://packages.simplifier.net/ihe.mhd.fhir/4.0.1
      #   # installMode: STORE_AND_INSTALL
      #   reloadExisting: false
      # de_basisprofil_r4:
      #   name: de.basisprofil.r4
      #   version: 1.4.0
      #   url: https://packages.simplifier.net/de.basisprofil.r4/1.4.0
      #   installMode: STORE_AND_INSTALL
      #   reloadExisting: false
      # kbv_basis:
      #   name: kbv.basis
      #   version: 1.6.0
      #   url: https://packages.simplifier.net/kbv.basis/1.6.0
      #   # installMode: STORE_AND_INSTALL
      #   reloadExisting: false
      # de_gematik_isik-basismodul:
      #   name: de.gematik.isik-basismodul
      #   version: 2.0.6
      #   url: https://packages.simplifier.net/de.gematik.isik-basismodul/2.0.6
      #   installMode: STORE_AND_INSTALL
      #   reloadExisting: false
      # de_medizininformatikinitiative_kerndatensatz_medikation:
      #   name: de.medizininformatikinitiative.kerndatensatz.medikation
      #   version: 1.0.10
      #   url: https://packages.simplifier.net/de.medizininformatikinitiative.kerndatensatz.medikation/1.0.10
      #   installMode: STORE_AND_INSTALL
      #   reloadExisting: false
      # dvmd_kdl_r4_2021:
      #   name: dvmd.kdl.r4.2021
      #   version: 2021.1.1
      #   url: https://packages.simplifier.net/dvmd.kdl.r4.2021/2021.1.1
      #   installMode: STORE_AND_INSTALL
      #   reloadExisting: false
      # de_gematik_isik-dokumentenaustausch:
      #   name: de.gematik.isik-dokumentenaustausch
      #   version: 2.0.1
      #   url: https://packages.simplifier.net/de.gematik.isik-dokumentenaustausch/2.0.1
      #   installMode: STORE_AND_INSTALL
      #   reloadExisting: false
      # de_gematik_isik-medikation:
      #   name: de.gematik.isik-medikation
      #   version: 2.0.2
      #   url: https://packages.simplifier.net/de.gematik.isik-medikation/2.0.2
      #   installMode: STORE_AND_INSTALL
      #   reloadExisting: false
      # de_gematik_isik-terminplanung:
      #   name: de.gematik.isik-terminplanung
      #   version: 2.0.4
      #   url: https://packages.simplifier.net/de.gematik.isik-terminplanung/2.0.4
      #   installMode: STORE_AND_INSTALL
      #   reloadExisting: false
      # de_gematik_isik-vitalparameter:
      #   name: de.gematik.isik-vitalparameter
      #   version: 2.0.3
      #   url: https://packages.simplifier.net/de.gematik.isik-vitalparameter/2.0.3
      #   installMode: STORE_AND_INSTALL
      #   reloadExisting: false
      # rki_demis_common:
      #   name: rki.demis.common
      #   version: 1.0.1
      #   url: https://packages.simplifier.net/rki.demis.common/1.0.1
      #   installMode: STORE_AND_INSTALL
      #   reloadExisting: false
      # rki_demis_disease:
      #   name: rki.demis.disease
      #   version: 1.3.0
      #   url: https://packages.simplifier.net/rki.demis.disease/1.3.0
      #   installMode: STORE_AND_INSTALL
      #   reloadExisting: false

spring:
  datasource:
    url: 'jdbc:postgresql://db:5432/hapi'
    username: admin
    password: admin
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate.dialect: ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgresDialect
      hibernate.search.enabled: true