services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
      - "8099:8080"

  fhir:
    container_name: fhirV4
    image: "hapiproject/hapi:latest"
    network_mode: service:nginx
    configs:
      - source: hapi
        target: /app/config/application.yaml
    depends_on:
      - db
      - nginx

  db:
    image: postgres
    # restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: hapi
    # use ephemerical database for now
    # volumes:
    #   - ./hapi.postgress.data:/var/lib/postgresql/data

configs:
  hapi:
     file: ./config/hapi.yaml
